"""Markdown report generated from the simulation results."""

from __future__ import annotations

from pathlib import Path

import pandas as pd


def _table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join([df.index.name or ""] + cols) + " |", "|" + "---|" * (len(cols) + 1)]
    for idx, row in df.iterrows():
        lines.append("| " + " | ".join([str(idx)] + [str(v) for v in row.tolist()]) + " |")
    return "\n".join(lines)


def _pct(a: float, b: float) -> str:
    return f"{100.0 * (a / b - 1.0):+.1f} %"


def write_report(path: Path, site, weather, results, grid, figures, weather_source: str = "synthetic") -> None:
    by = {r.scenario.key: r.kpis for r in results}
    land, fresh, saline = by["land"], by["fpv_fresh"], by["fpv_saline"]
    sal_mit = by["fpv_saline_mitigated"]
    base_results = [r for r in results if not r.scenario.key.endswith("_mitigated")]

    perf = pd.DataFrame(
        {
            r.scenario.label: {
                "Annual AC energy (MWh)": f"{r.kpis['energy_mwh']:.1f}",
                "Specific yield (kWh/kWp)": f"{r.kpis['specific_yield_kwh_kwp']:.0f}",
                "Performance ratio": f"{r.kpis['performance_ratio']:.3f}",
                "CUF, DC basis (%)": f"{r.kpis['cuf_dc_pct']:.2f}",
                "Plane-of-array irradiation (kWh/m²)": f"{r.kpis['poa_kwh_m2']:.0f}",
                "Mean daytime module temperature (°C)": f"{r.kpis['temp_module_daytime_mean']:.1f}",
                "Maximum module temperature (°C)": f"{r.kpis['temp_module_max']:.1f}",
                "Module - air, daytime mean (K)": f"{r.kpis['temp_module_minus_air_daytime']:.1f}",
                "Mean air RH at the array (%)": f"{r.kpis['rh_mean']:.1f}",
                "Hours with dew on the glass": f"{r.kpis['dew_hours']}",
                "Mean daytime soiling ratio": f"{r.kpis['soiling_ratio_mean']:.3f}",
            }
            for r in base_results
        }
    )
    perf.index.name = "Metric"

    loss = pd.DataFrame(
        {r.scenario.label: {k: f"{v:.2f}" for k, v in r.losses.items()} for r in base_results}
    )
    loss.index.name = "Loss stage (% of preceding stage)"

    deg = pd.DataFrame(
        {
            r.scenario.label: {
                "Intrinsic (%/yr)": f"{r.kpis['deg_base_pct_yr']:.2f}",
                "Temperature-humidity, Peck (%/yr)": f"{r.kpis['deg_temp_humidity_pct_yr']:.2f}",
                "PID (%/yr)": f"{r.kpis['deg_pid_pct_yr']:.2f}",
                "Salt / chloride corrosion (%/yr)": f"{r.kpis['deg_corrosion_pct_yr']:.2f}",
                "**Total (%/yr)**": f"**{r.kpis['deg_total_pct_yr']:.2f}**",
                "Time of wetness, ISO 9223 (h/yr)": f"{r.kpis['time_of_wetness_h']:.0f}",
                "Mean encapsulant RH (%)": f"{r.kpis['mean_encapsulant_rh']:.1f}",
                "Capacity in year 25 (%)": f"{r.kpis['year25_capacity_pct']:.1f}",
                "25-year energy (MWh)": f"{r.kpis['lifetime_energy_mwh']:.0f}",
                "LCOE (INR/kWh, illustrative)": f"{r.kpis['lcoe_inr_kwh']:.2f}",
            }
            for r in results
        }
    ).T
    deg.index.name = "Scenario"

    best = grid.loc[grid["lifetime_energy_mwh"].idxmax()]
    worst = grid.loc[grid["lifetime_energy_mwh"].idxmin()]

    piv = grid.pivot(index="dewpoint_offset", columns="salinity", values="lifetime_energy_mwh")
    salt_span = float((piv.max(axis=1) - piv.min(axis=1)).mean())
    moist_span = float((piv.max(axis=0) - piv.min(axis=0)).mean())
    driver = (
        f"salinity moves lifetime energy by about {salt_span:.0f} MWh and extra moisture by about {moist_span:.0f} MWh"
    )

    rel = lambda p: Path(p).relative_to(Path(path).parent).as_posix()  # noqa: E731
    fig = {Path(f).stem.split("_", 1)[0]: rel(f) for f in figures}

    text = f"""# Performance Analysis of a Floating Solar PV System for Humid and Saline Conditions

*Generated by `python -m fpv_analysis` - every number in this report is recomputed on each run.*

**Site:** {site.name} ({site.latitude:.2f}° N, {site.longitude:.2f}° E), hot, humid, coastal.
**Weather:** {weather_source} hourly year - GHI {weather['ghi'].sum() / 1000:.0f} kWh/m², mean air
temperature {weather['temp_air'].mean():.1f} °C, mean RH {weather['rh'].mean():.1f} %, rainfall
{weather['precip'].sum():.0f} mm.
**Plant:** 1 MWp DC per scenario, DC/AC ratio 1.2, mono-PERC modules (−0.35 %/K), south facing.

## 1. Key findings

1. **Water cooling pays off.** Floating modules run {land['temp_module_daytime_mean'] - fresh['temp_module_daytime_mean']:.1f} K
   cooler on average in daytime and {land['temp_module_max'] - fresh['temp_module_max']:.1f} K cooler at peak than land-mounted
   modules. The temperature loss falls from {land['loss_Module temperature']:.1f} % to {fresh['loss_Module temperature']:.1f} %.
2. **Freshwater FPV gives the highest year-1 yield**: {fresh['specific_yield_kwh_kwp']:.0f} kWh/kWp, against
   {land['specific_yield_kwh_kwp']:.0f} kWh/kWp on land ({_pct(fresh['energy_mwh'], land['energy_mwh'])}). PR is
   {fresh['performance_ratio']:.3f} against {land['performance_ratio']:.3f}. Lower soiling over water adds to the thermal gain. Extra
   cabling, wave-induced mismatch and lower availability take part of it back.
3. **Saline FPV loses the advantage.** Sea-salt deposits, cemented by deliquescence when the air is above 75 % RH, raise
   soiling to {saline['loss_Soiling (dust + salt)']:.1f} %. Together with higher DC and availability losses, year-1 yield is
   {saline['specific_yield_kwh_kwp']:.0f} kWh/kWp ({_pct(saline['energy_mwh'], land['energy_mwh'])} vs land).
4. **Humidity offsets the cooling benefit for degradation.** The air over water is more humid
   ({fresh['rh_mean']:.0f}-{saline['rh_mean']:.0f} % against {land['rh_mean']:.0f} %), and cooler modules sit closer to the dew
   point. Encapsulant moisture therefore rises ({land['mean_encapsulant_rh']:.0f} % → {fresh['mean_encapsulant_rh']:.0f} % →
   {saline['mean_encapsulant_rh']:.0f} %). That offsets the Arrhenius benefit of the lower temperature: temperature-humidity
   degradation is {land['deg_temp_humidity_pct_yr']:.2f} %/yr on land against {fresh['deg_temp_humidity_pct_yr']:.2f} %/yr
   (freshwater) and {saline['deg_temp_humidity_pct_yr']:.2f} %/yr (saline).
5. **Chloride corrosion and PID drive the extra loss in saline water.** Time of wetness reaches {saline['time_of_wetness_h']:.0f} h/yr.
   Total degradation is {saline['deg_total_pct_yr']:.2f} %/yr against {land['deg_total_pct_yr']:.2f} %/yr on land and
   {fresh['deg_total_pct_yr']:.2f} %/yr on freshwater. After 25 years a saline plant keeps {saline['year25_capacity_pct']:.1f} % of
   its capacity.
6. **Module choice is the main modelled lever in saline sites.** PID-resistant (IEC TS 62804-1) and salt-mist-hardened
   (IEC 61701) modules, with assumed reduction factors of 90 % and 50 %, cut saline FPV degradation
   to {sal_mit['deg_total_pct_yr']:.2f} %/yr and raise 25-year energy by
   {_pct(sal_mit['lifetime_energy_mwh'], saline['lifetime_energy_mwh'])} for an assumed +1.5 INR/Wp. LCOE goes from
   {saline['lcoe_inr_kwh']:.2f} to {sal_mit['lcoe_inr_kwh']:.2f} INR/kWh.
7. **Sensitivity.** Over the humidity × salinity grid, 25-year energy of the saline FPV ranges from
   {worst['lifetime_energy_mwh']:.0f} MWh (dew point +{worst['dewpoint_offset']:g} °C, {worst['salinity']:g}× salt) to
   {best['lifetime_energy_mwh']:.0f} MWh (+{best['dewpoint_offset']:g} °C, {best['salinity']:g}× salt). Across the full
   ranges swept, {driver}.
8. **Co-benefit.** The freshwater plant avoids about {fresh['water_saved_m3_yr']:,.0f} m³/yr of reservoir evaporation per MWp
   and needs no land.

## 2. Methodology

| Step | Model | Humidity / salinity coupling |
|---|---|---|
| Weather | Synthetic typical year from monthly normals (AR(1) clearness, rain, sea-breeze wind) or user CSV | Dew point held per day, so RH has a realistic diurnal cycle |
| Microclimate over water | Air pulled towards 30-day water temperature; dew point raised; wind ×1.15-1.25; albedo 0.07 | More moisture and lower diurnal air-temperature amplitude |
| Sun and irradiance | Spencer geometry, Erbs decomposition, Hay-Davies transposition, ASHRAE IAM | - |
| Spectrum | First Solar mono-Si spectral factor (air mass, precipitable water from Gueymard 1994) | Humid air gives a small c-Si spectral gain |
| Module temperature | Faiman, land u0/u1 = 25/6.84, FPV 35/8.0 W/m²K; night-sky radiative loss | Cooler modules → more dew |
| Dew | Forms within 1 K of the dew point, dries 4 K above it; 4 % optical loss while wet | Time of wetness |
| Soiling | Daily dust + salt mass balance, rain cleaning scaled by tilt, NaCl deliquescence cementation, cleaning every 15 days | Salt crust and wet adhesion |
| DC/AC | PVWatts DC (−0.35 %/K), wiring, mismatch, FPV wave motion, LID, PVWatts inverter with clipping, availability | - |
| Degradation | Intrinsic + Peck (Ea 0.79 eV, n 3, lagged encapsulant RH) + PID (Ea 0.9 eV, surface leakage) + chloride corrosion (ISO 9223 TOW × √Cl) | All three humidity terms |
| Economics | LCOE with discounted CAPEX/OPEX over 25 years | Degradation enters through lifetime energy |

Parameters are in `fpv_analysis/config.py`; their sources and the assumptions are listed in `README.md`.

## 3. Site climate

![Site climate]({fig['fig01']})

## 4. Year-1 performance

{_table(perf)}

![Module temperature]({fig['fig02']})

![Monthly energy]({fig['fig03']})

### Loss breakdown

{_table(loss)}

![Loss breakdown]({fig['fig04']})

![Soiling ratio]({fig['fig05']})

## 5. Degradation, lifetime energy and cost

{_table(deg)}

![Degradation]({fig['fig06']})

![Lifetime energy]({fig['fig07']})

## 6. Sensitivity to humidity and salinity (saline FPV)

The dew-point rise over water stands for extra humidity. Salinity scales salt soiling and chloride deposition together.

![Sensitivity degradation]({fig['fig08']})

![Sensitivity lifetime]({fig['fig09']})

## 7. Recommendations for humid and saline sites

* Specify **PID-resistant modules** qualified with **IEC TS 62804-1**, and **salt-mist** qualification to **IEC 61701**
  (severity 6 for marine sites). Use
  glass-glass modules with POE encapsulant where the budget allows, to limit moisture ingress.
* Use negative-pole grounding or night-time PID recovery on inverters. Choose IP68, marine-grade connectors and junction boxes.
* Use **HDPE floats, stainless steel 316 / hot-dip galvanised or aluminium fasteners**, and design to ISO 9223 class C5/CX at
  saline sites.
* Clean with demineralised water. At saline sites, tighten the cleaning interval in the dry season, when rain does not wash
  off the salt crust.
* Monitor module temperature, RH at the array, leakage current (insulation resistance) and soiling (reference cells) so that
  the model can be recalibrated with measured data.

## 8. Limitations

* The synthetic weather reproduces the monthly climatology, not a specific measured year. Use `--weather` with measured or TMY
  data for project-level estimates.
* The degradation reference rates are calibrated to field-survey magnitudes, not to measurements on this site. Relative
  comparisons are more robust than absolute values.
* Costs are illustrative Indian-market figures.
"""
    Path(path).write_text(text, encoding="utf-8")
